<a href="https://colab.research.google.com/github/Michael-Siri/AI-CAP4630/blob/master/HW4/Homework4Question2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Homework 4
#Question 2

The function maxpooling2d takes the 2 inputs of input_mat and s and returns output_mat.
The variables input_mat and output_mat are square matrices and s is an integer.
It should compute the maxpooling operation on input_mat using window of shape s times s.

Maxpooling: For each region in the matrix targetted by the filter of size S x S, it chooses the max element for a new matrix.

This function assumes s is the stride and the filter dimension of s times s.

In [0]:
import numpy as np

def maxpooling2d(input_mat, s):

    #Error Generation if size of Kernel is larger/returns empty array
    #Prints an error instead of raise exception since we want to return an empty array
  if(np.shape(input_mat) < (s,s)):
    print("Error: Filter is larger than the Input Matrix")
    return []
  
    #Width and Length of outerloop
  Width = np.shape(input_mat)[0]
  Length = np.shape(input_mat)[1]

    #Create output
    #Size of length or width divided by the filter size
  x = int(Width/s)
  output_mat = np.zeros((x,x))

    #Outerloop, increments by filtersize or strider
  for n in range(0,Width,s):
    for m in range(0,Length,s):
        #InnerLoop
      for i in range(s):
        for j in range(s):
          #Checks if the matrix is out of bounds, drops extra columns and rows
          try :
            output_mat[int(n/s)][int(m/s)] = max(output_mat[int(n/s)][int(m/s)], (input_mat[i+int(n)][j+int(m)]))
          except:
            pass
          

  return output_mat

# Test Cases
Extra test case where there are extra rows or columns

In [0]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


#Extra row and column test case
input_mat.append(np.array([[1, 2, 1, 2, 4],
                      [2, 4, 2, 1 , 4],
                      [1, 2, 4, 2, 4],
                      [2, 1, 2, 1, 4],
                      [2, 1, 2, 1, 4]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))




for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  # output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!
[[4. 2.]
 [2. 4.]]
Correct output!
