<a href="https://colab.research.google.com/github/Michael-Siri/AI-CAP4630/blob/master/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 1 : Problem 2

This code implements a function called mult_matrix which takes in a list of matrices in the form of numpy arrays and outputs their product.

If a matrix in the list is not compatible with the previous matrix it will be skipped and proceed to the next index in the list if it exists.

Two matrices of A and B are only compatible and able to multiply if the columns of matrix A is the same dimension as the rows of matrix B.





Product $C = $ Matrices $A*B$

# *IF*

 $A_{columns} = B_{rows}$

In [0]:
# Michael Siripongpibul CAP4630

import numpy as np
def mult_matrix(matrix):

    #check for empty list
    if len(matrix) == 0:
      print("Matrix list is empty.")
      return matrix

    length = len(matrix)-1
    result = matrix[0]

    #multiplys each index in matrix and prints out the incompatible indexes if it's not possible
    for x in range(length):
      try: 
        result = result.dot(matrix[x+1])
      except:
        print("Rows of matrix {} is not compatible with columns of matrix {}".format(x+2, x+1))
    return result 


# Test Cases

In [2]:

#Empty List
print("Empty case:")
Z = []
result = mult_matrix(Z) 
print(result);
print();


#Working Test case: A list of 2 matrices 
print("Working test case:")
A = np.array([[2,3,5], [4,6,5], [4,1,4],[4,1,4]])
B = np.array([[3,1],[7,8],[4,3]])
C = [A,B]
result = mult_matrix(C) 
print(result);
print();

#Failing Test case: A list of 2 incompatible matrices 
print("Failing test case:")
D = np.array([[2,3,5], [4,6,5], [4,1,4],[4,1,4]])
E = np.array([[3,1],[7,8],[4,3],[4,1]])
F = [D,E]
result = mult_matrix(F) 
print(result);
print();

#Failing Test case: A list of 3 matrices where it skips an incompatible matrix in the list 
print("Failing test case with skip:")
G = np.array([[2,3,5], [4,6,5], [4,1,4],[4,1,4]])
H = np.array([[3,1],[7,8],[4,3],[4,1]])
I = np.array([[3,1],[7,8],[4,3]])
J = [G,H,I]
result = mult_matrix(J) 
print(result);
print();




Empty case:
Matrix list is empty.
[]

Working test case:
[[47 41]
 [74 67]
 [35 24]
 [35 24]]

Failing test case:
Rows of matrix 2 is not compatible with columns of matrix 1
[[2 3 5]
 [4 6 5]
 [4 1 4]
 [4 1 4]]

Failing test case with skip:
Rows of matrix 2 is not compatible with columns of matrix 1
[[47 41]
 [74 67]
 [35 24]
 [35 24]]

