<a href="https://colab.research.google.com/github/Michael-Siri/AI-CAP4630/blob/master/HW_4/HW4Question1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 4
# Question 1

The function conv2d takes as input input_mat and kernel_mat and outputs output_mat. All variables are square matrices. It should compute the convolution of input_mat with the kernel kernel_mat using valid padding.

In convolution of the base matrix, all the pixels affected by the kernel action area is multiplied by each item in the kernel and added to a result in the output matrix. This continues from left to right and from top to bottom until the entire base matrix is covered.

If the Kernel is larger than the base Matrices, it should return an empty matrix.

In [0]:
import numpy as np

def conv2d(input_mat, kernel_mat):

    #Error Generation if size of Kernel is larger/returns empty array
    #Prints the error instead of raise exception since we want to return an empty array
  if(np.shape(input_mat) < np.shape(kernel_mat)):
    print("Error: Kernel is larger than the Input Matrix")
    return []
  
    #Flip Kernel
  kernel_mat = np.flip(kernel_mat)

    #Width and Length of outerloop
  Width = np.shape(input_mat)[0] - np.shape(kernel_mat)[0] + 1
  Length = np.shape(input_mat)[1] - np.shape(kernel_mat)[1] + 1

    #Create output
  output_mat = np.zeros((Width,Length))

    #Width and Lenght of innerloop
  Kernel_width = np.shape(kernel_mat)[0]
  Kernel_length = np.shape(kernel_mat)[1]

    #Outerloop
  for n in range(Width):
    for m in range(Length):
        #InnerLoop
      for i in range(Kernel_width):
        for j in range(Kernel_length):
          output_mat[n][m] = output_mat[n][m] + (input_mat[i+n][j+m] * kernel_mat[i][j])
  return output_mat

#Test Cases

In [4]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # # uncomment lines below (and comment line above) for generating test cases.
  # if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
  #   output_mat = []
  # else:
  #   output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")

[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!

Error: Kernel is larger than the Input Matrix
[]
Correct output!

